FROM node:16.13.2-alpine as build

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci

COPY frontend/ .

RUN npm rebuild esbuild

RUN npm run build

FROM caddy:2.4.5-alpine

COPY --from=build /app/dist /usr/share/caddy

COPY ./Caddyfile /etc/caddy/Caddyfile

EXPOSE 80

EXPOSE 443

RUN caddy validate --config /etc/caddy/Caddyfile