FROM golang:1.19.0 AS production

WORKDIR /app

COPY api/go.mod api/go.sum ./
RUN go mod download

COPY api/ .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o api .

EXPOSE 8080

CMD ["./api"]

